// Linux x86_64 errno values (see <asm-generic/errno-base.h> and <asm-generic/errno.h>)
pub const E = enum(usize) {
    SUCCESS = 0,
    PERM = 1, // Operation not permitted
    NOENT = 2, // No such file or directory
    SRCH = 3, // No such process
    INTR = 4, // Interrupted system call
    IO = 5, // I/O error
    NXIO = 6, // No such device or address
    @"2BIG" = 7, // Argument list too long
    NOEXEC = 8, // Exec format error
    BADF = 9, // Bad file number
    CHILD = 10, // No child processes
    AGAIN = 11, // Try again
    NOMEM = 12, // Out of memory
    ACCES = 13, // Permission denied
    FAULT = 14, // Bad address
    NOTBLK = 15, // Block device required
    BUSY = 16, // Device or resource busy
    EXIST = 17, // File exists
    XDEV = 18, // Cross-device link
    NODEV = 19, // No such device
    NOTDIR = 20, // Not a directory
    ISDIR = 21, // Is a directory
    INVAL = 22, // Invalid argument
    NFILE = 23, // File table overflow
    MFILE = 24, // Too many open files
    NOTTY = 25, // Not a typewriter
    TXTBSY = 26, // Text file busy
    FBIG = 27, // File too large
    NOSPC = 28, // No space left on device
    SPIPE = 29, // Illegal seek
    ROFS = 30, // Read-only file system
    MLINK = 31, // Too many links
    PIPE = 32, // Broken pipe
    DOM = 33, // Math argument out of domain
    RANGE = 34, // Math result not representable

    // Sockets / networking (the ones you'll actually hit soon)
    DEADLK = 35,
    NAMETOOLONG = 36,
    NOLCK = 37,
    NOSYS = 38,
    NOTEMPTY = 39,
    LOOP = 40,
    NOMSG = 42,
    IDRM = 43,
    CHRNG = 44,
    L2NSYNC = 45,
    L3HLT = 46,
    L3RST = 47,
    LNRNG = 48,
    UNATCH = 49,
    NOCSI = 50,
    L2HLT = 51,
    BADE = 52,
    BADR = 53,
    XFULL = 54,
    NOANO = 55,
    BADRQC = 56,
    BADSLT = 57,
    BFONT = 59,
    NOSTR = 60,
    NODATA = 61,
    TIME = 62,
    NOSR = 63,
    NONET = 64,
    NOPKG = 65,
    REMOTE = 66,
    NOLINK = 67,
    ADV = 68,
    SRMNT = 69,
    COMM = 70,
    PROTO = 71,
    MULTIHOP = 72,
    DOTDOT = 73,
    BADMSG = 74,
    OVERFLOW = 75,
    NOTUNIQ = 76,
    BADFD = 77,
    REMCHG = 78,
    LIBACC = 79,
    LIBBAD = 80,
    LIBSCN = 81,
    LIBMAX = 82,
    LIBEXEC = 83,
    ILSEQ = 84,
    RESTART = 85,
    STRPIPE = 86,
    USERS = 87,
    NOTSOCK = 88, // Socket operation on non-socket
    DESTADDRREQ = 89, // Destination address required
    MSGSIZE = 90, // Message too long
    PROTOTYPE = 91, // Protocol wrong type for socket
    NOPROTOOPT = 92, // Protocol not available
    PROTONOSUPPORT = 93, // Protocol not supported
    SOCKTNOSUPPORT = 94, // Socket type not supported
    OPNOTSUPP = 95, // Operation not supported on transport endpoint
    PFNOSUPPORT = 96, // Protocol family not supported
    AFNOSUPPORT = 97, // Address family not supported by protocol
    ADDRINUSE = 98, // Address already in use
    ADDRNOTAVAIL = 99, // Cannot assign requested address
    NETDOWN = 100, // Network is down
    NETUNREACH = 101, // Network is unreachable
    NETRESET = 102, // Network dropped connection on reset
    CONNABORTED = 103, // Software caused connection abort
    CONNRESET = 104, // Connection reset by peer
    NOBUFS = 105, // No buffer space available
    ISCONN = 106, // Transport endpoint is already connected
    NOTCONN = 107, // Transport endpoint is not connected
    SHUTDOWN = 108, // Cannot send after transport endpoint shutdown
    TOOMANYREFS = 109, // Too many references
    TIMEDOUT = 110, // Connection timed out
    CONNREFUSED = 111, // Connection refused
    HOSTDOWN = 112, // Host is down
    HOSTUNREACH = 113, // No route to host
    ALREADY = 114, // Operation already in progress
    INPROGRESS = 115, // Operation now in progress
    STALE = 116,
    UCLEAN = 117,
    NOTNAM = 118,
    NAVAIL = 119,
    ISNAM = 120,
    REMOTEIO = 121,
    DQUOT = 122,
    NOMEDIUM = 123,
    MEDIUMTYPE = 124,
    CANCELED = 125,
    NOKEY = 126,
    KEYEXPIRED = 127,
    KEYREVOKED = 128,
    KEYREJECTED = 129,
    OWNERDEAD = 130,
    NOTRECOVERABLE = 131,
    RFKILL = 132,
    HWPOISON = 133,

    _, // allow unknown values without erroring
};

/// Convert a raw negative syscall return value's magnitude into an E.
pub fn fromRet(ret: isize) E {
    return @enumFromInt(@as(usize, @intCast(-ret)));
}

pub const WOULDBLOCK = E.AGAIN;
